### ISSUE TITLE
Manage TWIG CACHE

### ISSUE THREAD

**Issue by Plou** [dummy-team/dummy-wordpress#17]
@toofff :
> "TWIG_CACHE_ENABLE"
    Find a method to enable and disable the cache twig like symfony.
    For example with a index_dev.php if possible

@Gregcop1 :
> it should be [link](https://developer.wordpress.org/themes/getting-started/setting-up-a-development-environment/) to an dev environment (maybe an hint here)

**Comment by Gregcop1** [comment]
Oops, my link fall into limbo... :) [Here it is](https://developer.wordpress.org/themes/getting-started/setting-up-a-development-environment/)
