### ISSUE TITLE
A new name: dummy-wordpress

### ISSUE THREAD

**Issue by Plou** [dummy-team/dummy-wordpress#45]
To keep the dummy suite consistent we should rename it. Like dummy-toolkit, dummy-wordpress could be a good name.

Any alternative ?

**Comment by Gregcop1** [comment]
Agree

**Comment by Gregcop1** [comment]
Or rename it dummy-neos and change tech :)

**Comment by shatimes** [comment]
+1 for dummy-wordpress or wordpress-dummy

**Comment by toofff** [comment]
Just `dummy-wordpress` because the team is named `dummy-team`

**Comment by shatimes** [comment]
Ok it's ready for

**Comment by Plou** [comment]
Github redirect the old name to this brand new, there shouldn't be any problems
